---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/cp -R public/. $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -R core $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -f .htaccess $DEPLOYPATH
